### ISSUE TITLE
打包之后，spin样式被覆盖，显示异常

### ISSUE THREAD

**Issue by fekata** [jingsam/iview-theme#4]
新生成的样式中,`display: table;`和`background-color: #fff;`影响到组件的正常显示
重新生成的样式
``` css
.ivu-spin-fix {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 8;
    display: table;
    width: 100%;
    height: 100%;
    background-color: #fff;
```

默认样式
``` css
.ivu-spin-fix {
    position: absolute;
    top: 0;
    left: 0;
    z-index: 8;
    width: 100%;
    height: 100%;
    background-color: hsla(0,0%,100%,.9);
}
```
